interface User {
    id: ID!
  email: String!
  username: String!
}

type Student implements User {
    id: ID!
  email: String!
  username: String!
  fullName: String!
}

type Teacher implements User {
    id: ID!
  email: String!
  username: String!
  age: Int!
}

input StudentInput {
    id: ID!
  email: String!
  username: String!
  fullName: String!
  password: String!
}



